### ISSUE TITLE
when sending messages for an instant chat moves down

### ISSUE THREAD

**Issue by Redundakitties** [NYRI4/Couve#21]
when sending messages for an instant chat moves down

I believe this is happening because of this line: 
```css
:root .channelTextAreaDisabled-1p2fQv {
  display: none;
} 
```
My guess is that when a message is sent, very briefly discord doesn't let you send another message, so the normal "you don't have permission to send messages in this channel" shows. But because the display is set to none everything shifts down. I've commented it out in my tweaks of the theme and that seems to fix it 👍
