### ISSUE TITLE
Profiles not showing correctly

### ISSUE THREAD

**Issue by wheredevilsplay** [NYRI4/Couve#23]
![image](https://user-images.githubusercontent.com/88294986/230515453-2b091cd4-57a4-4cec-88bf-440fa8bf5b73.png)
![image](https://user-images.githubusercontent.com/88294986/230515472-323ed0e1-e234-42e9-a126-8b67e465a139.png)

**Comment by Redundakitties** [comment]
I have a fix for this: 
try adding at the end of your css

```css
:root [class*="banner"] mask {
  display: none;
}
```
